### ISSUE TITLE
Option to use 'Optimal_Affected_Component' for component-failure pairs

### ISSUE THREAD

**Issue by henleo** [hpi-sam/rl-4-self-repair#23]
Could you please add the option to use 'Optimal_Affected_Component' instead of 'Optimal_Affected_Component_Uid' to create and sample the component-failure pairs to the DataHandler?

Best regards,
Leo

**Comment by brrrachel** [comment]
@henleo 
Implemented.
When initialising the DataHandler you can switch between selecting the data based on id or name by setting the param take_component_id. By default you will take the id.

If you want to load the Linear data and select the name, you have to type in:
DataHandler(environment = 'Linear', take_component_id = False)

**Comment by henleo** [comment]
@brrrachel
Thanks a lot :)
