### ISSUE TITLE
How to pick the initial state?

### ISSUE THREAD

**Issue by 2start** [hpi-sam/rl-4-self-repair#6]
Each permutation of failures might be a viable state.
However, we need a fixed action space for q-learning.

Brainstorming of possibilities:

_Choose a fixed initial state:_
+ Easy to train, we can just use unmodified q-learning.
- Unrealistic because we can usually not determine the exact order of failures.

_Mode each initial state as a state in the environment_:
+ Realistic, and we could assign a reward/cost from transitioning from each permutation to each other
- n*(n+1)! state transitions. Which is too much q-learning can't evaluate all the possible actions.

Idea: Limit the lookahead to a random subset of the states to choose the best action.

Other ideas are appreciated.

**Comment by MrBanhBao** [comment]
As we discussed we abandoned the idea of swapping components. Component-Failure-Pairs now can be repaired directly disregarding their order.
